# Generated by Django 5.1.6 on 2025-02-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0002_alter_student_email_alter_student_rollno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=25),
        ),
    ]
